In [34]:
# Setting up environment, test run with numpy

import numpy as np

# List
ar1 = [1,2,3]
# Print type of ar1
print(type(ar1))

<class 'list'>


In [35]:
# ar1 to numpy array
ar2 = np.array(ar1)
type(ar2)


numpy.ndarray

In [36]:
# ar3 as array defined as a range (start, end, stepSize), default stepSize = 1, creates integers
ar3 = np.arange(0,10)
print(ar3)

[0 1 2 3 4 5 6 7 8 9]


In [39]:
ar4 = np.arange(0,12.4,4.1)
print(ar4)

[ 0.   4.1  8.2 12.3]


In [40]:
# creates and fills ar5 array with 0 at different shape(row col), creates floats (0.) by default
ar5 = np.zeros(shape = (4,5)) # or np.zeros((4,5))
print(ar5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
type(0) #int
type(0.) #float

float

In [42]:
ar6 = np.ones((4,5))
print(ar6)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
# Generate random number
# Provide seed value to generate same random numbers everytime (for a particular star and end of range and for a particular seed value)
np.random.seed(10)
# Generate n random numbers (integers)
n = 5
ar7 = np.random.randint(20,85,n) # 20 = start(inclusive), 100 = end(exclusive), n = number of outcomes
print(ar7)
print(type(ar7))

[29 35 84 48 49]
<class 'numpy.ndarray'>


In [69]:
# Generate different random numbers everytime (since no seed value here)
ar8 = np.random.randint(20,100,n)
print(ar8)

[28 93 20 60 56]


In [75]:
# Print max value of an array, index of the max value of an array
print(ar8.max())
print(ar8.argmax())

93
1


In [76]:
# Print mix value of an array, index of the mix value of an array
print(ar8.min())
print(ar8.argmin())

20
2


In [77]:
# Print mean/average of an array
print(ar8.mean())

51.4


In [79]:
# Reshape an array (Change dimensions of an array). Note : Array dimensions should make sense wrt original array otherwise gives error. One idea : oldrow*oldcol = newrow*newcol
ar8.shape #Prints shape of an array. e.g (5,) means single row array with 5 elements

(5,)

In [86]:
# Reshaping
ar8.reshape(5,1) #doesn't save the changed shape of ar8 to ar8 (since no =)
ar8 = ar8.reshape(5,1) #save the changed shape, new shape(dimentions) = (5*1)
print(ar8)

[[28]
 [93]
 [20]
 [60]
 [56]]


In [89]:
# concatenate together arange and reshaping array commands
# a = np.arange(0,100) ; a=np.reshape(25,4) can be clubbed together like below
ar9 = np.arange(0,100).reshape(25,4)
print(ar9)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]
 [64 65 66 67]
 [68 69 70 71]
 [72 73 74 75]
 [76 77 78 79]
 [80 81 82 83]
 [84 85 86 87]
 [88 89 90 91]
 [92 93 94 95]
 [96 97 98 99]]


In [90]:
# printing element in ar9 at row=3,col=4
print(ar9[3,3])

15


In [91]:
# slicing to store/display conditional row-col values, or get some chunks of matrix/multi-d array based on some condition
# slicing can replace loops to access elements in array based on some condition
ar9[:,2] # diplay all col values of col=2 of ar9,(:) means everything, (a:b) means starting from a till b, (:b) means starting till b,(a:) means starting from a till end

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

In [92]:
ar9[:,2].shape #This is 1-d array with single row (no column), e.g (25,) means array of 25 val

(25,)

In [99]:
ar9[:,2].reshape(25,1).shape #This is multi-d array with row and column, e.g (25,1) means 25 row and 1 col

(25,)

In [100]:
ar9[2,:] # entire col of row 2

array([ 8,  9, 10, 11])

In [101]:
ar9[:] # all rows and cols

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [102]:
ar9[:,:] # all rows and cols

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59],
       [60, 61, 62, 63],
       [64, 65, 66, 67],
       [68, 69, 70, 71],
       [72, 73, 74, 75],
       [76, 77, 78, 79],
       [80, 81, 82, 83],
       [84, 85, 86, 87],
       [88, 89, 90, 91],
       [92, 93, 94, 95],
       [96, 97, 98, 99]])

In [104]:
ar9[1:3,:] # all elements of row 1(inclusive) to row 3(exclusive)

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
ar9[1:5,2] # elements of col 2 of (row 1 to row 5)

array([ 6, 10, 14, 18])

In [107]:
ar9[1:5,0:2] # elements from (col 0 to col 2) of (row 1 to row 5)

array([[ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [110]:
ar9[1:5,0:2] = 3 # all elements in the given range = 3
print(ar9) 

[[ 0  1  2  3]
 [ 3  3  6  7]
 [ 3  3 10 11]
 [ 3  3 14 15]
 [ 3  3 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]
 [48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]
 [64 65 66 67]
 [68 69 70 71]
 [72 73 74 75]
 [76 77 78 79]
 [80 81 82 83]
 [84 85 86 87]
 [88 89 90 91]
 [92 93 94 95]
 [96 97 98 99]]


In [112]:
ar10 = ar9 # shallow copy, both variables refer to same memory. Any changes to ar10 will change ar9
ar10[0,0] = 100
print(ar9[0,0])
ar11 = ar10.copy() #deep copy, ar11 is new independent variable, data of ar10 is copied in new memory refered by ar11 and both variable are independent
ar11[0,0] = 50
print(ar11[0,0])
print(ar10[0,0])
print(ar9[0,0])

100
50
100
100
